### ISSUE TITLE
browser tab shows htmlized buffer, not rendered html

### ISSUE THREAD

**Issue by titaniumbones** [netguy204/imp.el#36]
I had htis problem once before and cannot remember how I fixed it, or if it just somehow went a way by accident.  When I tyr to view html buffers using impatient mode, I don't see the html itself; instead, I get a picture of the buffer, rendered as HTML (see image below).

Inspecting the source, I see that the document in the content iframe contains a comment `<!-- created by htmlize-1.51 in css mode.-->`.

Any idea what might be causing this? seems like maybe 
![htmlized output](https://user-images.githubusercontent.com/364340/33676871-ec4b1894-da84-11e7-814d-cb2a57e86dcd.png)

**Comment by cicerojones** [comment]
@titaniumbones I had this problem as well.

After reading [this comment](https://github.com/netguy204/imp.el/blob/48e6c4842b1fc2657a3c6c23029f89e35fafc859/impatient-mode.el#L23) in the `impatient-mode.el` source, I tried calling `imp-toggle-htmlize` and the .html file was now again being rendered in real-time.

However, it appears you have to call this function on each file you are editing? Something appears to be amiss...perhaps on our end? Seems vaguely related to [this issue](https://github.com/netguy204/imp.el/issues/27), which was resolved without comment.

PS. This is all with everything recently installed from MELPA and with emacs (27.0.50) installed from HEAD via `homebrew`

**Comment by netguy204** [comment]
Let me know what you come up with. I don't use impatient-mode anymore but
am happy to vet and apply patches if you guys figure out what's going wrong.

**Comment by cicerojones** [comment]
I'll see if I anything turns up with continued usage. Is it naive to assume the issue may be a simple one if all is solved by simply toggling `htmlize` explictly?  

Either way, thanks again for the package--I hadn't experienced the peculiar joy of WYSIWYG editing in emacs before! And I'm on the hunt for a good, live-coding workflow that use emacs and org-mode (esp. for Quil/Processing and/or Clojurescript). Is it all just a bit of anachronistic fun now? 😛

**Comment by netguy204** [comment]
impatient mode tries to detect how it should serve the buffer and shouldn't
be defaulting to htmlize something that's obviously already html... so it
sounds like a bug.

Sure! Glad it's still finding use. I really enjoyed making it and using it.
Nowadays I spend my time debugging interactions with a stateful backend so
impatient-mode isn't a good fit for my day-to-day.

**Comment by titaniumbones** [comment]
Sorry for the delay responding folks, I lost track of htis thread. My problem was just that I started using mhtml-mode instead of web-mode, and needed to reset  `imp-default-user-filters`:

```
  (setq imp-default-user-filters
        '((html-mode . nil)
          (web-mode . nil)
          (mhtml-mode . nil)))
```

Now it works again! thanks so much for this tool, it makes a huge difference.

**Comment by titaniumbones** [comment]
@netguy204 do you use something else instead? Should I be switching?  :-)

**Comment by netguy204** [comment]
Use what works for you! Can you send a PR with that change? Seems like a
new reasonable default.
